//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticaDepozit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductOrders = new HashSet<ProductOrder>();
        }
    
        public string OrderID { get; set; }
        public string userID { get; set; }
        public string Status { get; set; }
        public string TotalPrice { get; set; }
        public string PlacedData { get; set; }
    
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public virtual User User { get; set; }
    }
}
